version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mysecretpassword
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432

  
  backend:
    build:
      context: ./backend
    ports:
      - "5002:5002"
    environment:
      - DB_USER=mysecretpassword
      - DB_PASS=example
      - DB_NAME=example
      - DB_HOST=db

  frontend:
    build:
      context: ./banking-frontend
      args:
        - REACT_APP_API_HOST=backend
    ports:
      - "3000:3000"

  bot:
    build:
      context: ./challenge-bot
    environment:
      - DB_USER=mysecretpassword
      - DB_PASS=example
      - DB_NAME=example
      - DB_HOST=db