version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx/conf.d/
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend
   
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mysecretpassword
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
    networks:
      - backend

  
  backend:
    build:
      context: ./backend
    ports:
      - "5002:5002"
    environment:
      - DB_USER=mysecretpassword
      - DB_PASS=example
      - DB_NAME=example
      - DB_HOST=db
    networks:
      - backend

  frontend:
    build:
      context: ./banking-frontend
      args:
        - REACT_APP_API_URL=http://testserver:8081/graphql
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  bot:
    build:
      context: ./challenge-bot
    environment:
      - DB_USER=mysecretpassword
      - DB_PASS=example
      - DB_NAME=example
      - DB_HOST=db
    extra_hosts:
      - "testserver:172.17.0.1"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge